name: citemesh-backend
region: nyc

services:
  - name: api
    github:
      repo: hemalbadola/CiteMesh
      branch: main
      deploy_on_push: true
    
    source_dir: backend
    
    # Use Dockerfile for more reliable builds
    dockerfile_path: backend/Dockerfile
    
    http_port: 8080
    
    instance_count: 1
    instance_size_slug: basic-xxs
    
    envs:
      - key: FIREBASE_PROJECT_ID
        value: citemesh
      - key: DATABASE_URL
        value: sqlite:///./app.db
      - key: PORT
        value: "8080"
      - key: OPENALEX_BASE_URL
        value: https://api.openalex.org
        scope: RUN_TIME
      - key: PYTHON_VERSION
        value: "3.11.9"
        scope: BUILD_TIME
    
    health_check:
      http_path: /health
    
    routes:
      - path: /
